
spring:
  application:    name: CMSforce
  datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@testproject3.cptggcrmj2t4.us-east-2.rds.amazonaws.com:1521:ORCL
      username: john
      password: password
  jpa:
     hibernate:
      show-sql: false
       
logging:
  config:
  file: /home/ec2-user/.jenkins/workspace/CMSforce/CMSforce/src/main/resources/ErrorLog.html
  
  
  pattern:
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
   
    
    com.revature: error, info
    org.hibernate: error, warn
    org.apache.catalina: off
    com.zaxxer.hikari: off

       
server.servlet.contextPath: /CMSforce
server:
  port: 9001

eureka:

  client:

    service-url:

      defaultZone: http://172.16.112.206:8761/eureka

  instance:

    lease-expiration-duration-in-seconds: 2

    lease-renewal-interval-in-seconds: 1      




  
          
      



